#include "reduction_data.h"

vector<vector<string>> reductions = {
    {"cannot", "can", "not"},
    {"d'ye", "do", "you"},
    {"gimme", "give", "me"},
    {"gotta", "got", "to"},
    {"more'n", "more", "than"},
    {"'tis", "it", "is"},
    {"'twas", "it", "was"},
    {"coulda", "could", "have"},
    {"musta", "must", "have"},
    {"shoulda", "should", "have"},
    {"woulda", "would", "have"},
    {"lotta", "lot", "of"},
    {"kinda", "kind", "of"},
    {"outta", "out", "of"},
    {"sorta", "sort", "of"},
    {"gonna", "going", "to"},
    {"hafta", "have", "to"},
    {"wanna", "want", "to"},
    {"oughta", "ought", "to"},
    {"didja", "did", "you"},
    {"d'ya", "do", "you"},
    {"doncha", "do", "n't", "you"},
    {"getcha", "get", "you"},
    {"wouldja", "would", "you"},
    {"bout", "about"},
    {"aright", "alright"},
    {"aight", "alright"},
    {"ima", "i", "'m", "going", "to"},
    {"i'ma", "i", "'m", "going", "to"},
    {"imma", "i", "'m", "going", "to"},
    {"i'mma", "i", "'m", "going", "to"},
    {"innit", "is", "n't", "it"},
    {"lemme", "let", "me"},
    {"prolly", "probably"},
    {"probly", "probably"},
    {"trynna", "trying", "to"},
    {"wanna", "want", "a"},
    {"whassup", "what", "is", "up"},
    {"wassup", "what", "is", "up"},
    {"sup", "what", "is", "up"},
    {"whatcha", "what", "are", "you"},
    {"whatcha", "what", "have", "you"},
    {"whaddaya", "what", "do", "you"},
    {"whaddaya", "what", "are", "you"},
};

