#include "americanizer_data.h"

// Automatically generated file -- do not edit!

namespace americanizer_data {

string S2Z_LIST =
    "acclimatisation "
    "acclimatise "
    "acclimatised "
    "acclimatising "
    "aggrandisement "
    "agonise "
    "agonised "
    "agonising "
    "agonisingly "
    "amortisable "
    "amortisation "
    "amortise "
    "amortised "
    "amortising "
    "analyse "
    "analysed "
    "analysing "
    "anglicise "
    "anglicised "
    "anglicising "
    "annualised "
    "antagonise "
    "antagonised "
    "antagonising "
    "apologise "
    "apologised "
    "apologising "
    "appetiser "
    "appetising "
    "appetisingly "
    "authorise "
    "authorised "
    "authorising "
    "baptise "
    "baptised "
    "baptising "
    "bowdlerise "
    "bowdlerised "
    "bowdlerising "
    "breathalyse "
    "breathalysed "
    "breathalyser "
    "breathalysing "
    "brutalise "
    "brutalised "
    "brutalising "
    "canalise "
    "canalised "
    "canalising "
    "cannibalise "
    "cannibalised "
    "cannibalising "
    "canonise "
    "canonised "
    "canonising "
    "capitalise "
    "capitalised "
    "capitalising "
    "caramelise "
    "caramelised "
    "caramelising "
    "carbonise "
    "carbonised "
    "carbonising "
    "catalyse "
    "catalysed "
    "catalysing "
    "categorise "
    "categorised "
    "categorising "
    "cauterise "
    "cauterised "
    "cauterising "
    "centralise "
    "centralised "
    "centralising "
    "characterise "
    "characterised "
    "characterising "
    "circularise "
    "circularised "
    "circularising "
    "civilise "
    "civilised "
    "civilising "
    "collectivise "
    "collectivised "
    "collectivising "
    "colonisation "
    "colonise "
    "colonised "
    "coloniser "
    "colonising "
    "commercialise "
    "commercialised "
    "commercialising "
    "compartmentalise "
    "compartmentalised "
    "compartmentalising "
    "computerise "
    "computerised "
    "computerising "
    "conceptualise "
    "conceptualised "
    "conceptualising "
    "contextualise "
    "contextualised "
    "contextualising "
    "cosier "
    "cosily "
    "cosy "
    "criminalise "
    "criminalised "
    "criminalising "
    "criticise "
    "criticised "
    "criticising "
    "decentralisation "
    "decentralise "
    "decentralised "
    "decentralising "
    "decriminalisation "
    "decriminalise "
    "decriminalised "
    "decriminalising "
    "dehumanisation "
    "dehumanise "
    "dehumanised "
    "dehumanising "
    "demilitarisation "
    "demilitarise "
    "demilitarised "
    "demilitarising "
    "demobilisation "
    "demobilise "
    "demobilised "
    "demobilising "
    "democratisation "
    "democratise "
    "democratised "
    "democratising "
    "demonise "
    "demonised "
    "demonising "
    "demoralisation "
    "demoralise "
    "demoralised "
    "demoralising "
    "denationalisation "
    "denationalise "
    "denationalised "
    "denationalising "
    "deodorise "
    "deodorised "
    "deodorising "
    "deputise "
    "deputised "
    "deputising "
    "digitise "
    "digitised "
    "digitising "
    "dramatisation "
    "dramatise "
    "dramatised "
    "dramatising "
    "economise "
    "economised "
    "economising "
    "editorialise "
    "editorialised "
    "editorialising "
    "empathise "
    "empathised "
    "empathising "
    "energise "
    "energised "
    "energising "
    "epitomise "
    "epitomised "
    "epitomising "
    "equalisation "
    "equalise "
    "equalised "
    "equaliser "
    "equalising "
    "eulogise "
    "eulogised "
    "eulogising "
    "evangelise "
    "evangelised "
    "evangelising "
    "exorcise "
    "exorcised "
    "exorcising "
    "extemporisation "
    "extemporise "
    "extemporised "
    "extemporising "
    "externalisation "
    "externalise "
    "externalised "
    "externalising "
    "factorise "
    "factorised "
    "factorising "
    "familiarisation "
    "familiarise "
    "familiarised "
    "familiarising "
    "feminise "
    "feminised "
    "feminising "
    "fertilisation "
    "fertilise "
    "fertilised "
    "fertiliser "
    "fertilising "
    "fictionalisation "
    "fictionalise "
    "fictionalised "
    "fictionalising "
    "finalisation "
    "finalise "
    "finalised "
    "finalising "
    "formalisation "
    "formalise "
    "formalised "
    "formalising "
    "fraternisation "
    "fraternise "
    "fraternised "
    "fraternising "
    "galvanise "
    "galvanised "
    "galvanising "
    "generalisation "
    "generalise "
    "generalised "
    "generalising "
    "ghettoise "
    "ghettoised "
    "ghettoising "
    "glamorise "
    "glamorised "
    "glamorising "
    "globalisation "
    "globalise "
    "globalised "
    "globalising "
    "harmonisation "
    "harmonise "
    "harmonised "
    "harmonising "
    "homogenise "
    "homogenised "
    "homogenising "
    "humanise "
    "humanised "
    "humanising "
    "hybridise "
    "hybridised "
    "hybridising "
    "hypnotise "
    "hypnotised "
    "hypnotising "
    "idealisation "
    "idealise "
    "idealised "
    "idealising "
    "idolise "
    "idolised "
    "idolising "
    "immobilisation "
    "immobilise "
    "immobilised "
    "immobiliser "
    "immobilising "
    "immortalise "
    "immortalised "
    "immortalising "
    "immunisation "
    "immunise "
    "immunised "
    "immunising "
    "individualise "
    "individualised "
    "individualising "
    "initialise "
    "initialised "
    "initialising "
    "intellectualise "
    "intellectualised "
    "intellectualising "
    "internalisation "
    "internalise "
    "internalised "
    "internalising "
    "internationalisation "
    "internationalise "
    "internationalised "
    "internationalising "
    "ionisation "
    "ionise "
    "ionised "
    "ioniser "
    "ionising "
    "italicise "
    "italicised "
    "italicising "
    "itemise "
    "itemised "
    "itemising "
    "jeopardise "
    "jeopardised "
    "jeopardising "
    "legalisation "
    "legalise "
    "legalised "
    "legalising "
    "legitimise "
    "legitimised "
    "legitimising "
    "liberalisation "
    "liberalise "
    "liberalised "
    "liberalising "
    "lionisation "
    "lionise "
    "lionised "
    "lionising "
    "liquidise "
    "liquidised "
    "liquidiser "
    "liquidising "
    "localise "
    "localised "
    "localising "
    "magnetise "
    "magnetised "
    "magnetising "
    "marginalisation "
    "marginalise "
    "marginalised "
    "marginalising "
    "materialisation "
    "materialise "
    "materialised "
    "materialising "
    "maximisation "
    "maximise "
    "maximised "
    "maximising "
    "mechanisation "
    "mechanise "
    "mechanised "
    "mechanising "
    "memorialise "
    "memorialised "
    "memorialising "
    "memorise "
    "memorised "
    "memorising "
    "metabolise "
    "metabolised "
    "metabolising "
    "militarise "
    "militarised "
    "militarising "
    "miniaturisation "
    "miniaturise "
    "miniaturised "
    "miniaturising "
    "minimise "
    "minimised "
    "minimising "
    "mobilisation "
    "mobilise "
    "mobilised "
    "mobilising "
    "modernise "
    "modernised "
    "modernising "
    "monopolisation "
    "monopolise "
    "monopolised "
    "monopolising "
    "moralise "
    "moralised "
    "moralising "
    "motorised "
    "nationalisation "
    "nationalise "
    "nationalised "
    "nationalising "
    "naturalisation "
    "naturalise "
    "naturalised "
    "naturalising "
    "neutralisation "
    "neutralise "
    "neutralised "
    "neutralising "
    "normalisation "
    "normalise "
    "normalised "
    "normalising "
    "optimise "
    "optimised "
    "optimising "
    "organisation "
    "organisational "
    "organise "
    "organised "
    "organiser "
    "organising "
    "oxidisation "
    "oxidise "
    "oxidised "
    "oxidising "
    "paralyse "
    "paralysed "
    "paralysing "
    "particularise "
    "particularised "
    "particularising "
    "patronise "
    "patronised "
    "patronising "
    "patronisingly "
    "penalise "
    "penalised "
    "penalising "
    "plagiarise "
    "plagiarised "
    "plagiarising "
    "polarisation "
    "polarise "
    "polarised "
    "polarising "
    "politicisation "
    "politicise "
    "politicised "
    "politicising "
    "popularisation "
    "popularise "
    "popularised "
    "popularising "
    "prioritisation "
    "prioritise "
    "prioritised "
    "prioritising "
    "privatisation "
    "privatise "
    "privatised "
    "privatising "
    "propagandise "
    "propagandised "
    "propagandising "
    "publicise "
    "publicised "
    "publicising "
    "pulverisation "
    "pulverise "
    "pulverised "
    "pulverising "
    "radicalise "
    "radicalised "
    "radicalising "
    "randomise "
    "randomised "
    "randomising "
    "rationalisation "
    "rationalise "
    "rationalised "
    "rationalising "
    "realisable "
    "realisation "
    "realise "
    "realised "
    "realising "
    "recognisable "
    "recognisably "
    "recognisance "
    "recognise "
    "recognised "
    "recognising "
    "regularisation "
    "regularise "
    "regularised "
    "regularising "
    "reorganisation "
    "reorganise "
    "reorganised "
    "reorganising "
    "revitalise "
    "revitalised "
    "revitalising "
    "revolutionise "
    "revolutionised "
    "revolutionising "
    "ritualised "
    "romanticise "
    "romanticised "
    "romanticising "
    "tantalise "
    "tantalised "
    "tantalising "
    "tantalisingly "
    "temporise "
    "temporised "
    "temporising "
    "tenderise "
    "tenderised "
    "tenderising "
    "terrorise "
    "terrorised "
    "terrorising "
    "theorise "
    "theorised "
    "theorising "
    "traumatise "
    "traumatised "
    "traumatising "
    "trivialise "
    "trivialised "
    "trivialising "
    "tyrannise "
    "tyrannised "
    "tyrannising "
    "unauthorised "
    "uncivilised "
    "underutilised "
    "unionisation "
    "unionise "
    "unionised "
    "unionising "
    "unorganised "
    "unrecognisable "
    "unrecognised "
    "urbanisation "
    "urbanise "
    "urbanised "
    "urbanising "
    "utilisable "
    "utilisation "
    "utilise "
    "utilised "
    "utilising "
    "vandalise "
    "vandalised "
    "vandalising "
    "vaporisation "
    "vaporise "
    "vaporised "
    "vaporising "
    "verbalise "
    "verbalised "
    "verbalising "
    "victimisation "
    "victimise "
    "victimised "
    "victimising "
    "vocalisation "
    "vocalise "
    "vocalised "
    "vocalising "
    "vulcanised "
    "vulgarisation "
    "vulgarise "
    "vulgarised "
    "vulgarising "
    "womanise "
    "womanised "
    "womaniser "
    "womanising "
;

string TOKEN_PAIRS =
    "accessorise accessorize "
    "accessorised accessorized "
    "accessorises accessorizes "
    "accessorising accessorizing "
    "acclimatises acclimatizes "
    "accoutrements accouterments "
    "aeon eon "
    "aeons eons "
    "aerogramme aerogram "
    "aerogrammes aerograms "
    "aeroplane airplane "
    "aeroplanes airplanes "
    "aesthete esthete "
    "aesthetes esthetes "
    "aesthetic esthetic "
    "aesthetically esthetically "
    "aesthetics esthetics "
    "aetiology etiology "
    "ageing aging "
    "agonises agonizes "
    "almanack almanac "
    "almanacks almanacs "
    "aluminium aluminum "
    "amortisations amortizations "
    "amortises amortizes "
    "amphitheatre amphitheater "
    "amphitheatres amphitheaters "
    "anaemia anemia "
    "anaemic anemic "
    "anaesthesia anesthesia "
    "anaesthetic anesthetic "
    "anaesthetics anesthetics "
    "anaesthetise anesthetize "
    "anaesthetised anesthetized "
    "anaesthetises anesthetizes "
    "anaesthetising anesthetizing "
    "anaesthetist anesthetist "
    "anaesthetists anesthetists "
    "anaesthetize anesthetize "
    "anaesthetized anesthetized "
    "anaesthetizes anesthetizes "
    "anaesthetizing anesthetizing "
    "analogue analog "
    "analogues analogs "
    "analyses analyzes "
    "anglicises anglicizes "
    "antagonises antagonizes "
    "apologises apologizes "
    "appal appall "
    "appals appalls "
    "appetisers appetizers "
    "arbour arbor "
    "arbours arbors "
    "archaeological archeological "
    "archaeologically archeologically "
    "archaeologist archeologist "
    "archaeologists archeologists "
    "archaeology archeology "
    "ardour ardor "
    "armour armor "
    "armoured armored "
    "armourer armorer "
    "armourers armorers "
    "armouries armories "
    "armoury armory "
    "artefact artifact "
    "artefacts artifacts "
    "authorises authorizes "
    "axe ax "
    "backpedalled backpedaled "
    "backpedalling backpedaling "
    "bannister banister "
    "bannisters banisters "
    "baptises baptizes "
    "bastardise bastardize "
    "bastardised bastardized "
    "bastardises bastardizes "
    "bastardising bastardizing "
    "battleaxe battleax "
    "baulk balk "
    "baulked balked "
    "baulking balking "
    "baulks balks "
    "bedevilled bedeviled "
    "bedevilling bedeviling "
    "behaviour behavior "
    "behavioural behavioral "
    "behaviourism behaviorism "
    "behaviourist behaviorist "
    "behaviourists behaviorists "
    "behaviours behaviors "
    "behove behoove "
    "behoved behooved "
    "behoves behooves "
    "bejewelled bejeweled "
    "belabour belabor "
    "belaboured belabored "
    "belabouring belaboring "
    "belabours belabors "
    "bevelled beveled "
    "bevvies bevies "
    "bevvy bevy "
    "biassed biased "
    "biassing biasing "
    "bingeing binging "
    "bougainvillaea bougainvillea "
    "bougainvillaeas bougainvilleas "
    "bowdlerises bowdlerizes "
    "breathalysers breathalyzers "
    "breathalyses breathalyzes "
    "brutalises brutalizes "
    "buses busses "
    "busing bussing "
    "caesarean cesarean "
    "caesareans cesareans "
    "calibre caliber "
    "calibres calibers "
    "calliper caliper "
    "callipers calipers "
    "callisthenics calisthenics "
    "canalises canalizes "
    "cancellation cancelation "
    "cancellations cancelations "
    "cancelled canceled "
    "cancelling canceling "
    "candour candor "
    "cannibalises cannibalizes "
    "canonises canonizes "
    "capitalises capitalizes "
    "caramelises caramelizes "
    "carbonises carbonizes "
    "carolled caroled "
    "carolling caroling "
    "catalogue catalog "
    "catalogued cataloged "
    "catalogues catalogs "
    "cataloguing cataloging "
    "catalyses catalyzes "
    "categorises categorizes "
    "cauterises cauterizes "
    "cavilled caviled "
    "cavilling caviling "
    "centigramme centigram "
    "centigrammes centigrams "
    "centilitre centiliter "
    "centilitres centiliters "
    "centimetre centimeter "
    "centimetres centimeters "
    "centralises centralizes "
    "centre center "
    "centred centered "
    "centrefold centerfold "
    "centrefolds centerfolds "
    "centrepiece centerpiece "
    "centrepieces centerpieces "
    "centres centers "
    "channelled channeled "
    "channelling channeling "
    "characterises characterizes "
    "cheque check "
    "chequebook checkbook "
    "chequebooks checkbooks "
    "chequered checkered "
    "cheques checks "
    "chilli chili "
    "chimaera chimera "
    "chimaeras chimeras "
    "chiselled chiseled "
    "chiselling chiseling "
    "circularises circularizes "
    "civilises civilizes "
    "clamour clamor "
    "clamoured clamored "
    "clamouring clamoring "
    "clamours clamors "
    "clangour clangor "
    "clarinettist clarinetist "
    "clarinettists clarinetists "
    "collectivises collectivizes "
    "colonisers colonizers "
    "colonises colonizes "
    "colour color "
    "colourant colorant "
    "colourants colorants "
    "coloured colored "
    "coloureds coloreds "
    "colourful colorful "
    "colourfully colorfully "
    "colouring coloring "
    "colourize colorize "
    "colourized colorized "
    "colourizes colorizes "
    "colourizing colorizing "
    "colourless colorless "
    "colours colors "
    "commercialises commercializes "
    "compartmentalises compartmentalizes "
    "computerises computerizes "
    "conceptualises conceptualizes "
    "connexion connection "
    "connexions connections "
    "contextualises contextualizes "
    "cosies cozies "
    "cosiest coziest "
    "cosiness coziness "
    "councillor councilor "
    "councillors councilors "
    "counselled counseled "
    "counselling counseling "
    "counsellor counselor "
    "counsellors counselors "
    "crenellated crenelated "
    "criminalises criminalizes "
    "criticises criticizes "
    "crueller crueler "
    "cruellest cruelest "
    "crystallisation crystallization "
    "crystallise crystallize "
    "crystallised crystallized "
    "crystallises crystallizes "
    "crystallising crystallizing "
    "cudgelled cudgeled "
    "cudgelling cudgeling "
    "customise customize "
    "customised customized "
    "customises customizes "
    "customising customizing "
    "cypher cipher "
    "cyphers ciphers "
    "decentralises decentralizes "
    "decriminalises decriminalizes "
    "defence defense "
    "defenceless defenseless "
    "defences defenses "
    "dehumanises dehumanizes "
    "demeanour demeanor "
    "demilitarises demilitarizes "
    "demobilises demobilizes "
    "democratises democratizes "
    "demonises demonizes "
    "demoralises demoralizes "
    "denationalises denationalizes "
    "deodorises deodorizes "
    "depersonalise depersonalize "
    "depersonalised depersonalized "
    "depersonalises depersonalizes "
    "depersonalising depersonalizing "
    "deputises deputizes "
    "desensitisation desensitization "
    "desensitise desensitize "
    "desensitised desensitized "
    "desensitises desensitizes "
    "desensitising desensitizing "
    "destabilisation destabilization "
    "destabilise destabilize "
    "destabilised destabilized "
    "destabilises destabilizes "
    "destabilising destabilizing "
    "dialled dialed "
    "dialling dialing "
    "dialogue dialog "
    "dialogues dialogs "
    "diarrhoea diarrhea "
    "digitises digitizes "
    "disc disk "
    "discolour discolor "
    "discoloured discolored "
    "discolouring discoloring "
    "discolours discolors "
    "discs disks "
    "disembowelled disemboweled "
    "disembowelling disemboweling "
    "disfavour disfavor "
    "dishevelled disheveled "
    "dishonour dishonor "
    "dishonourable dishonorable "
    "dishonourably dishonorably "
    "dishonoured dishonored "
    "dishonouring dishonoring "
    "dishonours dishonors "
    "disorganisation disorganization "
    "disorganised disorganized "
    "distil distill "
    "distils distills "
    "dramatisations dramatizations "
    "dramatises dramatizes "
    "draught draft "
    "draughtboard draftboard "
    "draughtboards draftboards "
    "draughtier draftier "
    "draughtiest draftiest "
    "draughts drafts "
    "draughtsman draftsman "
    "draughtsmanship draftsmanship "
    "draughtsmen draftsmen "
    "draughtswoman draftswoman "
    "draughtswomen draftswomen "
    "draughty drafty "
    "drivelled driveled "
    "drivelling driveling "
    "duelled dueled "
    "duelling dueling "
    "economises economizes "
    "editorialises editorializes "
    "edoema edema "
    "empathises empathizes "
    "emphasise emphasize "
    "emphasised emphasized "
    "emphasises emphasizes "
    "emphasising emphasizing "
    "enamelled enameled "
    "enamelling enameling "
    "enamoured enamored "
    "encyclopaedia encyclopedia "
    "encyclopaedias encyclopedias "
    "encyclopaedic encyclopedic "
    "endeavour endeavor "
    "endeavoured endeavored "
    "endeavouring endeavoring "
    "endeavours endeavors "
    "energises energizes "
    "enrol enroll "
    "enrols enrolls "
    "enthral enthrall "
    "enthrals enthralls "
    "epaulette epaulet "
    "epaulettes epaulets "
    "epicentre epicenter "
    "epicentres epicenters "
    "epilogue epilog "
    "epilogues epilogs "
    "epitomises epitomizes "
    "equalisers equalizers "
    "equalises equalizes "
    "eulogises eulogizes "
    "evangelises evangelizes "
    "exorcises exorcizes "
    "extemporises extemporizes "
    "externalisations externalizations "
    "externalises externalizes "
    "factorises factorizes "
    "faecal fecal "
    "faeces feces "
    "familiarises familiarizes "
    "fantasise fantasize "
    "fantasised fantasized "
    "fantasises fantasizes "
    "fantasising fantasizing "
    "favour favor "
    "favourable favorable "
    "favourably favorably "
    "favoured favored "
    "favouring favoring "
    "favourite favorite "
    "favourites favorites "
    "favouritism favoritism "
    "favours favors "
    "feminises feminizes "
    "fertilisers fertilizers "
    "fertilises fertilizes "
    "fervour fervor "
    "fibre fiber "
    "fibreglass fiberglass "
    "fibres fibers "
    "fictionalisations fictionalizations "
    "fictionalises fictionalizes "
    "fillet filet "
    "filleted fileted "
    "filleting fileting "
    "fillets filets "
    "finalises finalizes "
    "flautist flutist "
    "flautists flutists "
    "flavour flavor "
    "flavoured flavored "
    "flavouring flavoring "
    "flavourings flavorings "
    "flavourless flavorless "
    "flavours flavors "
    "flavoursome flavorsome "
    "foetal fetal "
    "foetid fetid "
    "foetus fetus "
    "foetuses fetuses "
    "formalises formalizes "
    "fossilisation fossilization "
    "fossilise fossilize "
    "fossilised fossilized "
    "fossilises fossilizes "
    "fossilising fossilizing "
    "fraternises fraternizes "
    "fulfil fulfill "
    "fulfilment fulfillment "
    "fulfils fulfills "
    "funnelled funneled "
    "funnelling funneling "
    "galvanises galvanizes "
    "gambolled gamboled "
    "gambolling gamboling "
    "gaol jail "
    "gaolbird jailbird "
    "gaolbirds jailbirds "
    "gaolbreak jailbreak "
    "gaolbreaks jailbreaks "
    "gaoled jailed "
    "gaoler jailer "
    "gaolers jailers "
    "gaoling jailing "
    "gaols jails "
    "gases gasses "
    "gauge gage "
    "gauged gaged "
    "gauges gages "
    "gauging gaging "
    "generalisations generalizations "
    "generalises generalizes "
    "ghettoises ghettoizes "
    "gipsies gypsies "
    "glamorises glamorizes "
    "glamour glamor "
    "globalises globalizes "
    "glueing gluing "
    "goitre goiter "
    "goitres goiters "
    "gonorrhoea gonorrhea "
    "gramme gram "
    "grammes grams "
    "gravelled graveled "
    "grey gray "
    "greyed grayed "
    "greying graying "
    "greyish grayish "
    "greyness grayness "
    "greys grays "
    "grovelled groveled "
    "grovelling groveling "
    "groyne groin "
    "groynes groins "
    "gruelling grueling "
    "gruellingly gruelingly "
    "gryphon griffin "
    "gryphons griffins "
    "gynaecological gynecological "
    "gynaecologist gynecologist "
    "gynaecologists gynecologists "
    "gynaecology gynecology "
    "haematological hematological "
    "haematologist hematologist "
    "haematologists hematologists "
    "haematology hematology "
    "haemoglobin hemoglobin "
    "haemophilia hemophilia "
    "haemophiliac hemophiliac "
    "haemophiliacs hemophiliacs "
    "haemorrhage hemorrhage "
    "haemorrhaged hemorrhaged "
    "haemorrhages hemorrhages "
    "haemorrhaging hemorrhaging "
    "haemorrhoids hemorrhoids "
    "harbour harbor "
    "harboured harbored "
    "harbouring harboring "
    "harbours harbors "
    "harmonises harmonizes "
    "homoeopath homeopath "
    "homoeopathic homeopathic "
    "homoeopaths homeopaths "
    "homoeopathy homeopathy "
    "homogenises homogenizes "
    "honour honor "
    "honourable honorable "
    "honourably honorably "
    "honoured honored "
    "honouring honoring "
    "honours honors "
    "hospitalisation hospitalization "
    "hospitalise hospitalize "
    "hospitalised hospitalized "
    "hospitalises hospitalizes "
    "hospitalising hospitalizing "
    "humanises humanizes "
    "humour humor "
    "humoured humored "
    "humouring humoring "
    "humourless humorless "
    "humours humors "
    "hybridises hybridizes "
    "hypnotises hypnotizes "
    "hypothesise hypothesize "
    "hypothesised hypothesized "
    "hypothesises hypothesizes "
    "hypothesising hypothesizing "
    "idealises idealizes "
    "idolises idolizes "
    "immobilisers immobilizers "
    "immobilises immobilizes "
    "immortalises immortalizes "
    "immunises immunizes "
    "impanelled impaneled "
    "impanelling impaneling "
    "imperilled imperiled "
    "imperilling imperiling "
    "individualises individualizes "
    "industrialise industrialize "
    "industrialised industrialized "
    "industrialises industrializes "
    "industrialising industrializing "
    "inflexion inflection "
    "inflexions inflections "
    "initialises initializes "
    "initialled initialed "
    "initialling initialing "
    "instal install "
    "instalment installment "
    "instalments installments "
    "instals installs "
    "instil instill "
    "instils instills "
    "institutionalisation institutionalization "
    "institutionalise institutionalize "
    "institutionalised institutionalized "
    "institutionalises institutionalizes "
    "institutionalising institutionalizing "
    "intellectualises intellectualizes "
    "internalises internalizes "
    "internationalises internationalizes "
    "ionisers ionizers "
    "ionises ionizes "
    "italicises italicizes "
    "itemises itemizes "
    "jeopardises jeopardizes "
    "jewelled jeweled "
    "jeweller jeweler "
    "jewellers jewelers "
    "jewellery jewelry "
    "judgement judgment "
    "kilogramme kilogram "
    "kilogrammes kilograms "
    "kilometre kilometer "
    "kilometres kilometers "
    "labelled labeled "
    "labelling labeling "
    "labour labor "
    "laboured labored "
    "labourer laborer "
    "labourers laborers "
    "labouring laboring "
    "labours labors "
    "lacklustre lackluster "
    "legalises legalizes "
    "legitimises legitimizes "
    "leukaemia leukemia "
    "levelled leveled "
    "leveller leveler "
    "levellers levelers "
    "levelling leveling "
    "libelled libeled "
    "libelling libeling "
    "libellous libelous "
    "liberalises liberalizes "
    "licence license "
    "licenced licensed "
    "licences licenses "
    "licencing licensing "
    "likeable likable "
    "lionises lionizes "
    "liquidisers liquidizers "
    "liquidises liquidizes "
    "litre liter "
    "litres liters "
    "localises localizes "
    "louvre louver "
    "louvred louvered "
    "louvres louvers "
    "lustre luster "
    "magnetises magnetizes "
    "manoeuvrability maneuverability "
    "manoeuvrable maneuverable "
    "manoeuvre maneuver "
    "manoeuvred maneuvered "
    "manoeuvres maneuvers "
    "manoeuvring maneuvering "
    "manoeuvrings maneuverings "
    "marginalises marginalizes "
    "marshalled marshaled "
    "marshalling marshaling "
    "marvelled marveled "
    "marvelling marveling "
    "marvellous marvelous "
    "marvellously marvelously "
    "materialises materializes "
    "maximises maximizes "
    "meagre meager "
    "mechanises mechanizes "
    "mediaeval medieval "
    "memorialises memorializes "
    "memorises memorizes "
    "mesmerise mesmerize "
    "mesmerised mesmerized "
    "mesmerises mesmerizes "
    "mesmerising mesmerizing "
    "metabolises metabolizes "
    "metre meter "
    "metres meters "
    "micrometre micrometer "
    "micrometres micrometers "
    "militarises militarizes "
    "milligramme milligram "
    "milligrammes milligrams "
    "millilitre milliliter "
    "millilitres milliliters "
    "millimetre millimeter "
    "millimetres millimeters "
    "miniaturises miniaturizes "
    "minibuses minibusses "
    "minimises minimizes "
    "misbehaviour misbehavior "
    "misdemeanour misdemeanor "
    "misdemeanours misdemeanors "
    "misspelt misspelled "
    "mitre miter "
    "mitres miters "
    "mobilises mobilizes "
    "modelled modeled "
    "modeller modeler "
    "modellers modelers "
    "modelling modeling "
    "modernises modernizes "
    "moisturise moisturize "
    "moisturised moisturized "
    "moisturiser moisturizer "
    "moisturisers moisturizers "
    "moisturises moisturizes "
    "moisturising moisturizing "
    "monologue monolog "
    "monologues monologs "
    "monopolises monopolizes "
    "moralises moralizes "
    "mould mold "
    "moulded molded "
    "moulder molder "
    "mouldered moldered "
    "mouldering moldering "
    "moulders molders "
    "mouldier moldier "
    "mouldiest moldiest "
    "moulding molding "
    "mouldings moldings "
    "moulds molds "
    "mouldy moldy "
    "moult molt "
    "moulted molted "
    "moulting molting "
    "moults molts "
    "moustache mustache "
    "moustached mustached "
    "moustaches mustaches "
    "moustachioed mustachioed "
    "multicoloured multicolored "
    "nationalisations nationalizations "
    "nationalises nationalizes "
    "naturalises naturalizes "
    "neighbour neighbor "
    "neighbourhood neighborhood "
    "neighbourhoods neighborhoods "
    "neighbouring neighboring "
    "neighbourliness neighborliness "
    "neighbourly neighborly "
    "neighbours neighbors "
    "neutralises neutralizes "
    "normalises normalizes "
    "odour odor "
    "odourless odorless "
    "odours odors "
    "oesophagus esophagus "
    "oesophaguses esophaguses "
    "oestrogen estrogen "
    "offence offense "
    "offences offenses "
    "omelette omelet "
    "omelettes omelets "
    "optimises optimizes "
    "organisations organizations "
    "organisers organizers "
    "organises organizes "
    "orthopaedic orthopedic "
    "orthopaedics orthopedics "
    "ostracise ostracize "
    "ostracised ostracized "
    "ostracises ostracizes "
    "ostracising ostracizing "
    "outmanoeuvre outmaneuver "
    "outmanoeuvred outmaneuvered "
    "outmanoeuvres outmaneuvers "
    "outmanoeuvring outmaneuvering "
    "overemphasise overemphasize "
    "overemphasised overemphasized "
    "overemphasises overemphasizes "
    "overemphasising overemphasizing "
    "oxidises oxidizes "
    "paederast pederast "
    "paederasts pederasts "
    "paediatric pediatric "
    "paediatrician pediatrician "
    "paediatricians pediatricians "
    "paediatrics pediatrics "
    "paedophile pedophile "
    "paedophiles pedophiles "
    "paedophilia pedophilia "
    "palaeolithic paleolithic "
    "palaeontologist paleontologist "
    "palaeontologists paleontologists "
    "palaeontology paleontology "
    "panelled paneled "
    "panelling paneling "
    "panellist panelist "
    "panellists panelists "
    "paralyses paralyzes "
    "parcelled parceled "
    "parcelling parceling "
    "parlour parlor "
    "parlours parlors "
    "particularises particularizes "
    "passivisation passivization "
    "passivise passivize "
    "passivised passivized "
    "passivises passivizes "
    "passivising passivizing "
    "pasteurisation pasteurization "
    "pasteurise pasteurize "
    "pasteurised pasteurized "
    "pasteurises pasteurizes "
    "pasteurising pasteurizing "
    "patronises patronizes "
    "pedalled pedaled "
    "pedalling pedaling "
    "pedestrianisation pedestrianization "
    "pedestrianise pedestrianize "
    "pedestrianised pedestrianized "
    "pedestrianises pedestrianizes "
    "pedestrianising pedestrianizing "
    "penalises penalizes "
    "pencilled penciled "
    "pencilling penciling "
    "personalise personalize "
    "personalised personalized "
    "personalises personalizes "
    "personalising personalizing "
    "pharmacopoeia pharmacopeia "
    "pharmacopoeias pharmacopeias "
    "philosophise philosophize "
    "philosophised philosophized "
    "philosophises philosophizes "
    "philosophising philosophizing "
    "philtre filter "
    "philtres filters "
    "phoney phony "
    "plagiarises plagiarizes "
    "plough plow "
    "ploughed plowed "
    "ploughing plowing "
    "ploughman plowman "
    "ploughmen plowmen "
    "ploughs plows "
    "ploughshare plowshare "
    "ploughshares plowshares "
    "polarises polarizes "
    "politicises politicizes "
    "popularises popularizes "
    "pouffe pouf "
    "pouffes poufs "
    "practise practice "
    "practised practiced "
    "practises practices "
    "practising practicing "
    "praesidium presidium "
    "praesidiums presidiums "
    "pressurisation pressurization "
    "pressurise pressurize "
    "pressurised pressurized "
    "pressurises pressurizes "
    "pressurising pressurizing "
    "pretence pretense "
    "pretences pretenses "
    "primaeval primeval "
    "prioritises prioritizes "
    "privatisations privatizations "
    "privatises privatizes "
    "professionalisation professionalization "
    "professionalise professionalize "
    "professionalised professionalized "
    "professionalises professionalizes "
    "professionalising professionalizing "
    "programme program "
    "programmes programs "
    "prologue prolog "
    "prologues prologs "
    "propagandises propagandizes "
    "proselytise proselytize "
    "proselytised proselytized "
    "proselytiser proselytizer "
    "proselytisers proselytizers "
    "proselytises proselytizes "
    "proselytising proselytizing "
    "psychoanalyse psychoanalyze "
    "psychoanalysed psychoanalyzed "
    "psychoanalyses psychoanalyzes "
    "psychoanalysing psychoanalyzing "
    "publicises publicizes "
    "pulverises pulverizes "
    "pummelled pummel "
    "pummelling pummeled "
    "pyjama pajama "
    "pyjamas pajamas "
    "pzazz pizzazz "
    "quarrelled quarreled "
    "quarrelling quarreling "
    "radicalises radicalizes "
    "rancour rancor "
    "randomises randomizes "
    "rationalisations rationalizations "
    "rationalises rationalizes "
    "ravelled raveled "
    "ravelling raveling "
    "realisations realizations "
    "realises realizes "
    "recognises recognizes "
    "reconnoitre reconnoiter "
    "reconnoitred reconnoitered "
    "reconnoitres reconnoiters "
    "reconnoitring reconnoitering "
    "refuelled refueled "
    "refuelling refueling "
    "regularises regularizes "
    "remodelled remodeled "
    "remodelling remodeling "
    "remould remold "
    "remoulded remolded "
    "remoulding remolding "
    "remoulds remolds "
    "reorganisations reorganizations "
    "reorganises reorganizes "
    "revelled reveled "
    "reveller reveler "
    "revellers revelers "
    "revelling reveling "
    "revitalises revitalizes "
    "revolutionises revolutionizes "
    "rhapsodise rhapsodize "
    "rhapsodised rhapsodized "
    "rhapsodises rhapsodizes "
    "rhapsodising rhapsodizing "
    "rigour rigor "
    "rigours rigors "
    "rivalled rivaled "
    "rivalling rivaling "
    "romanticises romanticizes "
    "rumour rumor "
    "rumoured rumored "
    "rumours rumors "
    "sabre saber "
    "sabres sabers "
    "saltpetre saltpeter "
    "sanitise sanitize "
    "sanitised sanitized "
    "sanitises sanitizes "
    "sanitising sanitizing "
    "satirise satirize "
    "satirised satirized "
    "satirises satirizes "
    "satirising satirizing "
    "saviour savior "
    "saviours saviors "
    "savour savor "
    "savoured savored "
    "savouries savories "
    "savouring savoring "
    "savours savors "
    "savoury savory "
    "scandalise scandalize "
    "scandalised scandalized "
    "scandalises scandalizes "
    "scandalising scandalizing "
    "sceptic skeptic "
    "sceptical skeptical "
    "sceptically skeptically "
    "scepticism skepticism "
    "sceptics skeptics "
    "sceptre scepter "
    "sceptres scepters "
    "scrutinise scrutinize "
    "scrutinised scrutinized "
    "scrutinises scrutinizes "
    "scrutinising scrutinizing "
    "secularisation secularization "
    "secularise secularize "
    "secularised secularized "
    "secularises secularizes "
    "secularising secularizing "
    "sensationalise sensationalize "
    "sensationalised sensationalized "
    "sensationalises sensationalizes "
    "sensationalising sensationalizing "
    "sensitise sensitize "
    "sensitised sensitized "
    "sensitises sensitizes "
    "sensitising sensitizing "
    "sentimentalise sentimentalize "
    "sentimentalised sentimentalized "
    "sentimentalises sentimentalizes "
    "sentimentalising sentimentalizing "
    "sepulchre sepulcher "
    "sepulchres sepulchers "
    "serialisation serialization "
    "serialisations serializations "
    "serialise serialize "
    "serialised serialized "
    "serialises serializes "
    "serialising serializing "
    "sermonise sermonize "
    "sermonised sermonized "
    "sermonises sermonizes "
    "sermonising sermonizing "
    "sheikh sheik "
    "shovelled shoveled "
    "shovelling shoveling "
    "shrivelled shriveled "
    "shrivelling shriveling "
    "signalise signalize "
    "signalised signalized "
    "signalises signalizes "
    "signalising signalizing "
    "signalled signaled "
    "signalling signaling "
    "smoulder smolder "
    "smouldered smoldered "
    "smouldering smoldering "
    "smoulders smolders "
    "snivelled sniveled "
    "snivelling sniveling "
    "snorkelled snorkeled "
    "snorkelling snorkeling "
    "snowplough snowplow "
    "snowploughs snowplow "
    "socialisation socialization "
    "socialise socialize "
    "socialised socialized "
    "socialises socializes "
    "socialising socializing "
    "sodomise sodomize "
    "sodomised sodomized "
    "sodomises sodomizes "
    "sodomising sodomizing "
    "solemnise solemnize "
    "solemnised solemnized "
    "solemnises solemnizes "
    "solemnising solemnizing "
    "sombre somber "
    "specialisation specialization "
    "specialisations specializations "
    "specialise specialize "
    "specialised specialized "
    "specialises specializes "
    "specialising specializing "
    "spectre specter "
    "spectres specters "
    "spiralled spiraled "
    "spiralling spiraling "
    "splendour splendor "
    "splendours splendors "
    "squirrelled squirreled "
    "squirrelling squirreling "
    "stabilisation stabilization "
    "stabilise stabilize "
    "stabilised stabilized "
    "stabiliser stabilizer "
    "stabilisers stabilizers "
    "stabilises stabilizes "
    "stabilising stabilizing "
    "standardisation standardization "
    "standardise standardize "
    "standardised standardized "
    "standardises standardizes "
    "standardising standardizing "
    "stencilled stenciled "
    "stencilling stenciling "
    "sterilisation sterilization "
    "sterilisations sterilizations "
    "sterilise sterilize "
    "sterilised sterilized "
    "steriliser sterilizer "
    "sterilisers sterilizers "
    "sterilises sterilizes "
    "sterilising sterilizing "
    "stigmatisation stigmatization "
    "stigmatise stigmatize "
    "stigmatised stigmatized "
    "stigmatises stigmatizes "
    "stigmatising stigmatizing "
    "storey story "
    "storeys stories "
    "subsidisation subsidization "
    "subsidise subsidize "
    "subsidised subsidized "
    "subsidiser subsidizer "
    "subsidisers subsidizers "
    "subsidises subsidizes "
    "subsidising subsidizing "
    "succour succor "
    "succoured succored "
    "succouring succoring "
    "succours succors "
    "sulphate sulfate "
    "sulphates sulfates "
    "sulphide sulfide "
    "sulphides sulfides "
    "sulphur sulfur "
    "sulphurous sulfurous "
    "summarise summarize "
    "summarised summarized "
    "summarises summarizes "
    "summarising summarizing "
    "swivelled swiveled "
    "swivelling swiveling "
    "symbolise symbolize "
    "symbolised symbolized "
    "symbolises symbolizes "
    "symbolising symbolizing "
    "sympathise sympathize "
    "sympathised sympathized "
    "sympathiser sympathizer "
    "sympathisers sympathizers "
    "sympathises sympathizes "
    "sympathising sympathizing "
    "synchronisation synchronization "
    "synchronise synchronize "
    "synchronised synchronized "
    "synchronises synchronizes "
    "synchronising synchronizing "
    "synthesise synthesize "
    "synthesised synthesized "
    "synthesiser synthesizer "
    "synthesisers synthesizers "
    "synthesises synthesizes "
    "synthesising synthesizing "
    "syphon siphon "
    "syphoned siphoned "
    "syphoning siphoning "
    "syphons siphons "
    "systematisation systematization "
    "systematise systematize "
    "systematised systematized "
    "systematises systematizes "
    "systematising systematizing "
    "tantalises tantalizes "
    "tasselled tasseled "
    "technicolour technicolor "
    "temporises temporizes "
    "tenderises tenderizes "
    "terrorises terrorizes "
    "theatre theater "
    "theatregoer theatergoer "
    "theatregoers theatergoers "
    "theatres theaters "
    "theorises theorizes "
    "tonne ton "
    "tonnes tons "
    "towelled toweled "
    "towelling toweling "
    "toxaemia toxemia "
    "tranquillise tranquilize "
    "tranquillised tranquilized "
    "tranquilliser tranquilizer "
    "tranquillisers tranquilizers "
    "tranquillises tranquilizes "
    "tranquillising tranquilizing "
    "tranquillity tranquility "
    "tranquillize tranquilize "
    "tranquillized tranquilized "
    "tranquillizer tranquilizer "
    "tranquillizers tranquilizers "
    "tranquillizes tranquilizes "
    "tranquillizing tranquilizing "
    "tranquilly tranquility "
    "transistorised transistorized "
    "traumatises traumatizes "
    "travelled traveled "
    "traveller traveler "
    "travellers travelers "
    "travelling traveling "
    "travelogue travelog "
    "travelogues travelogs "
    "trialled trialed "
    "trialling trialing "
    "tricolour tricolor "
    "tricolours tricolors "
    "trivialises trivializes "
    "tumour tumor "
    "tumours tumors "
    "tunnelled tunneled "
    "tunnelling tunneling "
    "tyrannises tyrannizes "
    "tyre tire "
    "tyres tires "
    "unequalled unequaled "
    "unfavourable unfavorable "
    "unfavourably unfavorably "
    "unionises unionizes "
    "unravelled unraveled "
    "unravelling unraveling "
    "unrivalled unrivaled "
    "unsavoury unsavory "
    "untrammelled untrammeled "
    "urbanises urbanizes "
    "utilises utilizes "
    "valour valor "
    "vandalises vandalizes "
    "vaporises vaporizes "
    "vapour vapor "
    "vapours vapors "
    "verbalises verbalizes "
    "victimises victimizes "
    "videodisc videodisk "
    "videodiscs videodisks "
    "vigour vigor "
    "visualisation visualization "
    "visualisations visualizations "
    "visualise visualize "
    "visualised visualized "
    "visualises visualizes "
    "visualising visualizing "
    "vocalisations vocalizations "
    "vocalises vocalizes "
    "vulgarises vulgarizes "
    "waggon wagon "
    "waggons wagons "
    "watercolour watercolor "
    "watercolours watercolors "
    "weaselled weaseled "
    "weaselling weaseling "
    "westernisation westernization "
    "westernise westernize "
    "westernised westernized "
    "westernises westernizes "
    "westernising westernizing "
    "womanisers womanizers "
    "womanises womanizes "
    "woollen woolen "
    "woollens woolens "
    "woollies woolies "
    "woolly wooly "
    "worshipped worshiped "
    "worshipper worshiper "
    "worshipping worshiping "
    "yodelled yodeled "
    "yodelling yodeling "
    "yoghourt yogurt "
    "yoghourts yogurts "
    "yoghurt yogurt "
    "yoghurts yogurts "
;

}  // namespace americanizer_data
